name = "Enzyme_jll"
uuid = "7cc45869-7501-5eee-bdea-0790c847d4ef"
version = "0.0.237+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.10"
LazyArtifacts = "< 0.0.1, 1"
Libdl = "< 0.0.1, 1"
TOML = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
